### ISSUE TITLE
Build fails with gcc11

### ISSUE THREAD

**Issue by lgbaldoni** [keegancsmith/FUSEPod#2]
Trying (still!) to fix a build problem on openSUSE Tumbleweed. https://github.com/keegancsmith/FUSEPod/commit/ff7043291212525dfbf6495da0140d98f13ffc09 indeed fixes the problems with gcc10 but now the default compiler is gcc11, see [build log](https://github.com/keegancsmith/FUSEPod/files/7839494/fusepod_gcc11_j4.txt).

**Comment by keegancsmith** [comment]
Sorry, forgot to check with gcc11. Fixed by https://github.com/keegancsmith/FUSEPod/commit/ab85982388f4968e09bcd434a3a1e9ab77af42b9

As a reference for my future self, this is how I got gcc11 on nixos:

```
with import <nixpkgs> {};
gcc11Stdenv.mkDerivation {
  name = "fusepod-dev";
  buildInputs = [ pkg-config fuse libgpod ];
}
```
